;; 
;; 

;; Authored by effecting2 in 2006-2007.
;; This is free software distributed under the GPL Version 2 or newer.
;; It has no warranty. See the GNU General Public License for more
;; information.

;; This code is not part of GNU Emacs.

;; layout 3 frames as 4 windows, 2 row by 2 col, raster-scan order
;; almost full screen for 1600x1200

;; (setq my-layout3
;;   (frame-configuration
;;    (#<frame *scratch* 0x10ab9ed0>
;;             ((parent-id . 14878784)
;;              (display . ":0.0")
;;              (visibility . t)
;;              (icon-name)
;;              (outer-window-id . "35651913")
;;              (window-id . "35651915")
;;              (top . 610)
;;              (left . 0)
;;              (buffer-list #<buffer *scratch*> #<buffer *Messages*> #<buffer  *Minibuf-1*>)
;;              (unsplittable)
;;              (minibuffer . #<window 20 on  *Minibuf-0*>)
;;              (modeline . t)
;;              (width . 262)
;;              (height . 57)
;;              (name . "*scratch*")
;;              (background-mode . dark)
;;              (display-type . color)
;;              (scroll-bar-width . 0)
;;              (cursor-type . box)
;;              (auto-lower)
;;              (auto-raise)
;;              (icon-type . t)
;;              (wait-for-wm . t)
;;              (title)
;;              (buffer-predicate)
;;              (tool-bar-lines . 0)
;;              (menu-bar-lines . 0)
;;              (scroll-bar-background . "grey75")
;;              (scroll-bar-foreground)
;;              (right-fringe . 9)
;;              (left-fringe . 9)
;;              (line-spacing)
;;              (screen-gamma)
;;              (border-color . "white")
;;              (cursor-color . "white")
;;              (mouse-color . "white")
;;              (background-color . "black")
;;              (foreground-color . "white")
;;              (vertical-scroll-bars)
;;              (internal-border-width . 1)
;;              (border-width . 2)
;;              (font . "-*-*-medium-r-normal--10-*-*-*-*-*-fontset-startup"))
;;             #<window-configuration>)
;;    (#<frame *scratch* 0x10aab5f8>
;;             ((parent-id . 14878711)
;;              (display . ":0.0")
;;              (visibility . t)
;;              (icon-name)
;;              (outer-window-id . "35651885")
;;              (window-id . "35651887")
;;              (top . 0)
;;              (left . 806)
;;              (buffer-list #<buffer *scratch*>)
;;              (unsplittable)
;;              (minibuffer . #<window 17 on  *Minibuf-0*>)
;;              (modeline . t)
;;              (width . 128)
;;              (height . 59)
;;              (name . "*scratch*")
;;              (background-mode . dark)
;;              (display-type . color)
;;              (scroll-bar-width . 0)
;;              (cursor-type . box)
;;              (auto-lower)
;;              (auto-raise)
;;              (icon-type . t)
;;              (wait-for-wm . t)
;;              (title)
;;              (buffer-predicate)
;;              (tool-bar-lines . 0)
;;              (menu-bar-lines . 0)
;;              (scroll-bar-background . "grey75")
;;              (scroll-bar-foreground)
;;              (right-fringe . 9)
;;              (left-fringe . 9)
;;              (line-spacing)
;;              (screen-gamma)
;;              (border-color . "white")
;;              (cursor-color . "white")
;;              (mouse-color . "white")
;;              (background-color . "black")
;;              (foreground-color . "white")
;;              (vertical-scroll-bars)
;;              (internal-border-width . 1)
;;              (border-width . 2)
;;              (font . "-*-*-medium-r-normal--10-*-*-*-*-*-fontset-startup"))
;;             #<window-configuration>)
;;    (#<frame *ielm* 0x106444c8>
;;             ((parent-id . 14875689)
;;              (display . ":0.0")
;;              (visibility . t)
;;              (icon-name)
;;              (outer-window-id . "35651755")
;;              (window-id . "35651757")
;;              (top . 132)
;;              (left . 0)
;;              (buffer-list #<buffer *ielm*> #<buffer *scratch*> #<buffer  *Minibuf-1*>)
;;              (unsplittable)
;;              (minibuffer . #<window 10 on  *Minibuf-0*>)
;;              (modeline . t)
;;              (width . 130)
;;              (height . 46)
;;              (name . "*ielm*")
;;              (background-mode . dark)
;;              (display-type . color)
;;              (scroll-bar-width . 0)
;;              (cursor-type . box)
;;              (auto-lower)
;;              (auto-raise)
;;              (icon-type . t)
;;              (wait-for-wm . t)
;;              (title)
;;              (buffer-predicate)
;;              (tool-bar-lines . 0)
;;              (menu-bar-lines . 0)
;;              (scroll-bar-background . "grey75")
;;              (scroll-bar-foreground)
;;              (right-fringe . 9)
;;              (left-fringe . 9)
;;              (line-spacing)
;;              (screen-gamma)
;;              (border-color . "white")
;;              (cursor-color . "white")
;;              (mouse-color . "white")
;;              (background-color . "black")
;;              (foreground-color . "white")
;;              (vertical-scroll-bars)
;;              (internal-border-width . 1)
;;              (border-width . 2)
;;              (font . "-*-*-medium-r-normal--10-*-*-*-*-*-fontset-startup"))
;;             #<window-configuration>))
;;   )

(delete-other-frames)
(delete-other-windows)

(defun my-layout3 ()
  (let* ( (x (selected-frame))
          (y (make-frame-command))
          (z nil) ;;(make-frame-command) ))
          )

;;     (set-frame-size x 130 46)
;;     (set-frame-position x 0 132)
    
;;     (set-frame-size y 128 59)
;;     (set-frame-position y 806 0)
    
;;     (set-frame-size z 262 57)
;;     (set-frame-position z 0 610)

    (select-frame y)
    )
  )

(my-layout3)

;; window 4
;; (mutt "132x11")

;; ;; daemons
(fetchmail)
(gnuserv-start)
(server-start)

(require 'load-home)
(require 'load-work)

;;(mh-rmail)
